version: "3.9"
services:
  web:
    build: .
    container_name: web
    ports:
      - "3000:3000"
    environment:
      - PYTHON_SERVICE_URL=http://python-service:8000
      - R_SERVICE_URL=http://r-service:8000
    depends_on:
      - python-service
      - r-service
    networks:
      - stats-net

  python-service:
    build: ./app/python-service
    container_name: python_service
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - stats-net

  r-service:
    build: ./r-service
    container_name: r_service
    ports:
      - "8001:8000"
    networks:
      - stats-net

networks:
  stats-net:
    driver: bridge
